.TH lm 1 "2015-11-02"
.SH NAME
lm \- ls for music
.SH SYNOPSIS
.B lm
[ [\fB\-\-author\fR]
[\fB\-\-genre\fR]
[\fB\-\-album\fR]
[\fB\-\-track\fR] ]...
[\fB\-\-header\fR]
.IR file...
.SH DESCRIPTION
.B lm
is a little program who read multimedia metainformations, such as genre, title, track, album and also artist for a music
.IR file
and prints it in human-readable way.
It’s seen as an a music dedicated ls varient.
.PP
The output list always diplay informations in the following order: Title name, Track number, Author name, Album, Genre.
.SH OPTIONS
.TP
\fB\-\-author\fR
Sort the given files by author.
.TP
\fB\-\-genre\fR
Sort the given files by genre.
.TP
\fB\-\-track\fR
Sort the given files by track number.
.TP
\fB\-\-header\fR
Display a header on the top of the list remembring the colomn information type.
.SH SEE ALSO
.BR ffprobe (1)
.SH AUTHOR
The mayor part of
.B lm
is writen by Fauve (aka Idriss al Idrissi) <http://taniere.info> and could be find in Github at <https://github.com/FauveNoir/lm/>.
